In [2]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [3]:
raw_data_frame=pd.DataFrame({'Precio':[],'NCuartos':[],'Area':[],'NBaños':[],'Distrito':[], 'Amoblado':[],'Mantenimiento':[],'Cochera':[],'Azotea':[]})
count = 1
while count <= 10:
  if count == 1 :
    url='https://www.laencontre.com.pe/alquiler/t-departamentos/lima'
  else:
    url=str('https://www.laencontre.com.pe/alquiler/t-departamentos/lima/p_'+str(count))
  page=requests.get(url)
  soup=BeautifulSoup(page.content,'html.parser')
  for link in soup.find_all('a'):
    if str(link.get('href'))[1:9] == 'inmueble' :
        url_page='https://www.laencontre.com.pe/'+str(link.get('href'))[1:] 
        page_dep=requests.get(url_page)
        soup_page_dep=BeautifulSoup(page_dep.content,'html.parser')
        precio_t = soup_page_dep.find_all('div', class_ ='price')
        ncuartos_t=soup_page_dep.find_all('li', class_ ='bedrooms')
        nbanos_t=soup_page_dep.find_all('li', class_ ='bathrooms')
        distrito_t=soup_page_dep.find_all('li', class_ ='elementBC detail-bread-li')
        area_t=soup_page_dep.find_all('li', class_ ='dimensions')
        extra_t=soup_page_dep.find_all('li', class_ ='tick')
        precio_v=list()
        ncuartos_v=list()
        nbanos_v=list()
        distrito_v=list()
        area_v=list()
        amob_v=list()
        mantenimiento_v=list()
        cochera_v=list()
        azotea_v=list()
        for i in precio_t :
          precio_v.append(i.text)
        for i in ncuartos_t :
          ncuartos_v.append(i.text)
        for i in nbanos_t :
          nbanos_v.append(i.text)
        for i in distrito_t:
          distrito_v.append(i.text)
        for i in area_t:
          area_v.append(i.text)
        for i in extra_t: 
          if i.text[0:19]=='Valor Mantenimiento':
            mantenimiento_v.append(i.text)
          elif i.text[0:4]=='Amob':
            amob_v.append(i.text)
          elif i.text[0:11]=='Cantidad de':
            cochera_v.append(i.text)
          elif i.text[0:10]=='Acceso a A':
            azotea_v.append(i.text)

        raw_data_frame=raw_data_frame.append({'Precio': precio_v ,'NCuartos': ncuartos_v[0:1],'Area':area_v[0:1],'NBaños':nbanos_v[0:1],
                                              'Distrito':distrito_v[4:5],'Amoblado':amob_v,'Mantenimiento':mantenimiento_v,'Cochera':cochera_v,'Azotea':azotea_v}, ignore_index=True)
  count += 1
#ruta='C:\Users\Andres\Documents\Proyectos\CEBI PAPER\'
#raw_data_frame.to_csv("datos.csv")
raw_data_frame

,Precio,NCuartos,Area,NBaños,Distrito,Amoblado,Mantenimiento,Cochera,Azotea
0,"[\n$ 1,600\n]",[3 Habitaciones],[180m2],[3.5 Baños],[\nSan Isidro\n\n],[],[Valor Mantenimiento (S/): 850],[Cantidad de estacionamientos: 2],[]
1,[\n$ 860\n],[3 Habitaciones],[90m2],[2.5 Baños],[\nSan Isidro\n\n],[Amoblado: Semi-amoblado],[Valor Mantenimiento (S/): 350],[Cantidad de estacionamientos: 1],[]
2,[\n$ 850\n],[3 Habitaciones],[125m2],[3 Baños],[\nSantiago de Surco\n\n],[Amoblado: Amoblado],[Valor Mantenimiento (S/): 280],[Cantidad de estacionamientos: 1],[Acceso a Azotea]
3,"[\n$ 1,100\n]",[1 Hab],[70m2],[1 Baño],[\nSan Isidro\n\n],[Amoblado: Amoblado],"[Valor Mantenimiento (S/): 450, Valor Mantenim...",[Cantidad de estacionamientos: 1],[]
4,"[\n$ 1,000\n]",[3 Habitaciones],[115m2],[3 Baños],[\nSantiago de Surco\n\n],[Amoblado: Amoblado],[Valor Mantenimiento (S/): 400],[Cantidad de estacionamientos: 1],[]
...,...,...,...,...,...,...,...,...,...
291,[\n$ 980\n],[4 Habitaciones],[238m2],[3.5 Baños],[\nSantiago de Surco\n\n],[Amoblado: Sin amoblar],[],[],[Acceso a Azotea]
292,[\n$ 667.13\n],[2 Habitaciones],[100m2],[1 Baño],[\nSan Borja\n\n],[Amoblado: Sin amoblar],[Valor Mantenimiento (S/): 300],[Cantidad de estacionamientos: 1],[]
293,"[\n$ 1,190\n]",[1 Hab],[92m2],[2 Baños],[\nBarranco\n\n],[Amoblado: Amoblado],"[Valor Mantenimiento (S/): 500, Valor Mantenim...",[Cantidad de estacionamientos: 1],[]
294,[\n$ 650\n],[2 Habitaciones],[71m2],[2 Baños],[\nLa Molina\n\n],[Amoblado: Sin amoblar],[Valor Mantenimiento (S/): 150],[Cantidad de estacionamientos: 1],[]
295,"[\n$ 1,500\n]",[3 Habitaciones],[145m2],[3 Baños],[\nSan Isidro\n\n],[Amoblado: Amoblado],[Valor Mantenimiento (S/): 430],[Cantidad de estacionamientos: 1],[]

In [3]:
def limpieza_datos(row):
    columnas = raw_data_frame.columns
    
    for x in columnas:
        if isinstance(row[x], list) and len(row[x]) ==0 :
            row[x] = ""
        else:
            row[x] = row[x][0].replace("\n", "")

    return row

def limpiar_datos(df_raw):
    df = df_raw.copy()
    
    df = raw_data_frame.apply(limpieza_datos, axis=1)
    df["Precio"] = df["Precio"].str.replace("$","").str.replace(",","").str.replace('Desde$','').str.replace('(Precio a consultar)','0')
    df["Precio"] = pd.to_numeric(df["Precio"])
    df["NCuartos"] = df["NCuartos"].str.extract('(\d+)')
    df["Area"] = df["Area"].str.extract('(\d+)')
    df["NBaños"] = df["NBaños"].str.extract('(\d*\.?\d+)')
    df["Mantenimiento"] = df["Mantenimiento"].str.extract('(\d+)')
    df["Cochera"] = df["Cochera"].str.extract('(\d+)')

    df["Amoblado"] = df["Amoblado"].str.strip()
    df["Azotea"] = df["Azotea"].str.strip()
    df["Distrito"] = df["Distrito"].str.strip()

    df["Azotea"] = df["Azotea"].apply(lambda x: "si" if x == "Acceso a Azotea" else "no")
    
    return df

In [4]:
df_clean = limpiar_datos(raw_data_frame)
df_clean

,Precio,NCuartos,Area,NBaños,Distrito,Amoblado,Mantenimiento,Cochera,Azotea
0,3000.00,3,260,4,Santa Maria del Mar,Amoblado: Amoblado,350,2,si
1,1100.00,1,70,1,San Isidro,Amoblado: Amoblado,450,1,no
2,1600.00,3,180,3.5,San Isidro,,850,2,no
3,860.00,3,90,2.5,San Isidro,Amoblado: Semi-amoblado,350,1,no
4,850.00,3,125,3,Santiago de Surco,Amoblado: Amoblado,280,1,si
...,...,...,...,...,...,...,...,...,...
174,513.38,1,56,NaN,San Isidro,Amoblado: Amoblado,NaN,NaN,no
175,900.00,2,85,2,Surquillo,Amoblado: Amoblado,255,NaN,no
176,1100.00,3,140,2.5,Miraflores,Amoblado: Sin amoblar,300,1,no
177,832.50,2,83,2,Miraflores,Amoblado: Amoblado,300,1,no
178,277.50,2,55,1,San Borja,Amoblado: Sin amoblar,50,NaN,no